name: End to End tests command with option

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    code_analysis:
        strategy:
            fail-fast: false

        name: End to End tests command with option
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v6

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   uses: "ramsey/composer-install@v3"

            # test various commands with options
            -   working-directory: e2e/command-with-option
                run: |
                    # other command
                    ../../bin/rector help
                    php ../../bin/rector help

                    # with explicit "process" command
                    ../../bin/rector process --output-format json --dry-run
                    ../../bin/rector process --output-format=json --dry-run
                    php ../../bin/rector process --output-format json --dry-run
                    php ../../bin/rector process --output-format=json --dry-run

                    ../../bin/rector process some_file.php --output-format json
                    ../../bin/rector process some_file.php --output-format=json
                    php ../../bin/rector process some_file.php --output-format json
                    php ../../bin/rector process some_file.php --output-format=json

                    # with implicit process command
                    ../../bin/rector --output-format json --dry-run
                    ../../bin/rector --output-format=json --dry-run
                    php ../../bin/rector --output-format json --dry-run
                    php ../../bin/rector --output-format=json --dry-run

                    ../../bin/rector some_file.php --output-format json
                    ../../bin/rector some_file.php --output-format=json
                    php ../../bin/rector some_file.php --output-format json
                    php ../../bin/rector some_file.php --output-format=json

