name: Rector

on:
    pull_request: null

# don't run on forks at all
if: github.event.pull_request.head.repo.full_name == 'rectorphp/rector-src'

jobs:
    rector:
        strategy:
            fail-fast: false
            matrix:
                paths:
                    - src tests rules-tests packages packages-tests
                    - rules
                    - config utils

        runs-on: ubuntu-latest
        timeout-minutes: 8

        steps:
            -
                uses: actions/checkout@v3
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    # PHP 8.1 is required, so Rector's code is PHP 8.1 compatible even after refactoring
                    php-version: 8.1
                    coverage: none

            -   run: composer install --no-progress --ansi

            ## here can't be --dry-run, as the change results in error code 1 and stops the job without commiting in the future
            -   run: bin/rector process ${{ matrix.paths }} --ansi

            # see https://github.com/rectorphp/rector/issues/7579
            -
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: '[ci-review] Rector Rectify'
                    commit_author: 'GitHub Action <actions@github.com>'
                    commit_user_email: 'action@github.com'
