name: Rector

on:
    pull_request: null

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
    rector:
        strategy:
            fail-fast: false
            matrix:
                paths:
                    - src tests rules-tests packages packages-tests
                    - rules
                    - config utils

        runs-on: ubuntu-latest
        timeout-minutes: 8

        if: github.event.pull_request.head.repo.full_name == 'rectorphp/rector-src'
        steps:
            -
                uses: actions/checkout@v3
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            - run: echo "run on ${{ github.event.pull_request.head.repo.full_name }}"

            -
                uses: shivammathur/setup-php@v2
                with:
                    # PHP 8.1 is required, so Rector's code is PHP 8.1 compatible even after refactoring
                    php-version: 8.1
                    coverage: none

            -   run: composer install --no-progress --ansi

            ## First run Rector - here can't be --dry-run !!! it would stop the job with it and not commit anything in the future
            -   run: bin/rector process ${{ matrix.paths }} --ansi

            -
                # commit only to core contributors who have repository access
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: '[ci-review] Rector Rectify'
                    commit_author: 'GitHub Action <actions@github.com>'
                    commit_user_email: 'action@github.com'
